//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIDGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUID
    {
        public int ID { get; set; }
        public List<string> GUID1 = new List<string>();
        public Nullable<System.DateTimeOffset> DateAdded { get; set; }
    }
}
